name: CI
on:
  push:
    branches: ['**']
    tags-ignore: ['**']
  pull_request:
jobs:
  activate:
    if: "!endsWith(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-26.04
    steps:
    - name: Proceed
      run: echo ok go
  build:
    needs: activate
    strategy:
      matrix:
        os: [ubuntu-26.04]
        ruby: ['3.2', '3.3', '3.4', '4.0']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Configure Bundler
      run: bundle config --local path .bundle/gems
    - name: Install dependencies
      run: bundle --jobs 3 --retry 3
    - name: Run tests
      run: bundle exec ruby -w $(bundle exec ruby -e 'print File.join Gem.bindir, %q(rake)') spec
    - name: Convert sample document
      run: bundle exec ruby -w $(bundle exec ruby -e 'print File.join Gem.bindir, %q(asciidoctor)') -r asciidoctor-mathematical sample.adoc
